trigger:
- main

pr:
  branches:
    include:
    - main
  drafts: false

jobs:
- job: IntegrationTestRocm
  displayName: Integration test ROCm
  strategy:
    matrix:
      rocm6.2:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-dev-rocm6.2

  pool:
    name: mscclpp-rocm
  container:
    image: $[ variables['containerImage'] ]
    options: --privileged --ipc=host --security-opt seccomp=unconfined --group-add video --ulimit memlock=-1:-1

  steps:
  - task: Bash@3
    name: Build
    displayName: Build
    inputs:
      targetType: 'inline'
      script: |
        mkdir build && cd build
        CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_BUILD_TYPE=Release -DBYPASS_GPU_CHECK=ON -DUSE_ROCM=ON ..
        make -j
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: InstallRcclTest
    displayName: Install rccl-test
    inputs:
      targetType: 'inline'
      script: |
        git clone https://github.com/ROCm/rccl-tests.git
        cd rccl-tests
        make MPI=1 MPI_HOME=/usr/local/mpi HIP_HOME=/opt/rocm -j
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: InstallDep
    displayName: Install dependencies
    inputs:
     targetType: 'inline'
     script: |
      set -e
      git clone https://github.com/Azure/msccl-tools.git
      cd msccl-tools
      pip3 install .

  - task: Bash@3
    name: GenerateExectionFile
    displayName: Generate execution file
    inputs:
     targetType: 'inline'
     script: |
      set -e
      git clone https://$(GIT_USER):$(GIT_PAT)@msazure.visualstudio.com/DefaultCollection/One/_git/azure-mscclpp
      cd azure-mscclpp
      git checkout binyli/ci
      mkdir execution-files
      python3 algos/allreduce_mi300_packet.py 8 8 > execution-files/allreduce_mi300_packet.json
      python3 algos/allreduce_mi300_sm_mscclpp.py 8 8 > execution-files/allreduce_mi300_sm_mscclpp.json

  - task: Bash@3
    name: AllReduceTest
    displayName: Run mscclpp AllReduce test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        sudo /usr/local/mpi/bin/mpirun --allow-run-as-root -np 8 --bind-to numa -x MSCCLPP_DEBUG=WARN -x LD_PRELOAD="$(pwd)/build/apps/nccl/libmscclpp_nccl.so" \
          -x ALLREDUCE_SMALL_MSG_BOUNDARY=32K -x ALLREDUCE_LARGE_MSG_BOUNDARY=1M ./rccl-tests/build/all_reduce_perf -b 1K -e 1G -f 2 -d half -G 20 -w 10 -n 100
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Bash@3
    name: AllReduceExecutionFileTest
    displayName: Run mscclpp AllReduce execution file test
    inputs:
      targetType: 'inline'
      script: |
        set -e
        export PATH=/usr/local/mpi/bin:$PATH
        sleep 1d
        sudo /usr/local/mpi/bin/mpirun --allow-run-as-root -np 8 --bind-to numa -x MSCCLPP_DEBUG=WARN -x LD_PRELOAD="$(pwd)/build/apps/nccl/libmscclpp_nccl.so" \
          -x ALLREDUCE_SMALL_MSG_BOUNDARY=32K -x ALLREDUCE_LARGE_MSG_BOUNDARY=1M ./rccl-tests/build/all_reduce_perf -b 1K -e 1G -f 2 -d half -G 20 -w 10 -n 100
      workingDirectory: '$(System.DefaultWorkingDirectory)'
