name: C++ Lint

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  run-linters:
    runs-on: ubuntu-20.04

    steps:
    - name: Check git version
      env:
        min-ver: "2.18"
      run: dpkg --compare-versions $(git version | awk '{print $3}') ge ${{ env.min-ver }}

    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Install ClangFormat
      run: sudo apt-get install -y clang-format-12

    - name: Run cpplint
      run: |
        CPPSOURCES=$(find ./ -regextype posix-extended -regex '.*\.(c|cpp|h|hpp|cc|cxx|cu)' -not -path "./build/*" -not -path "./python/*")
        PYTHONCPPSOURCES=$(find ./python/src/ -regextype posix-extended -regex '.*\.(c|cpp|h|hpp|cc|cxx|cu)')
        clang-format-12 -style=file --verbose --Werror --dry-run $(CPPSOURCES)
        clang-format-12 --dry-run $(PYTHONCPPSOURCES)
